// Not part of the service contract. These messages exist only so ./wire can
// decode one User's bytes as three different shapes and show you what the
// decoder actually matches on. Nothing registers them, nothing serves them.
//
// Every message here describes the same three strings. They differ only in
// which names and which numbers they attach to them, which is precisely the
// axis the wire format cares about and the axis a reader of the .proto does
// not notice.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: wire_demo.proto

package wirepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RenamedUser has the same field NUMBERS as users.v1.User and completely
// different field NAMES. Decoding a User into this works perfectly: the
// names on the wire are not there, so there is nothing to disagree with.
type RenamedUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName     string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	EmailAddress string `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
}

func (x *RenamedUser) Reset() {
	*x = RenamedUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenamedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamedUser) ProtoMessage() {}

func (x *RenamedUser) ProtoReflect() protoreflect.Message {
	mi := &file_wire_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenamedUser.ProtoReflect.Descriptor instead.
func (*RenamedUser) Descriptor() ([]byte, []int) {
	return file_wire_demo_proto_rawDescGZIP(), []int{0}
}

func (x *RenamedUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RenamedUser) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RenamedUser) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

// ShuffledUser has the same field NAMES as users.v1.User and rotated field
// NUMBERS. This is what "someone edited the field numbers" looks like to a
// client that has not been regenerated. Decoding a User into this succeeds
// and every value lands in the wrong field.
type ShuffledUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ShuffledUser) Reset() {
	*x = ShuffledUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShuffledUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffledUser) ProtoMessage() {}

func (x *ShuffledUser) ProtoReflect() protoreflect.Message {
	mi := &file_wire_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffledUser.ProtoReflect.Descriptor instead.
func (*ShuffledUser) Descriptor() ([]byte, []int) {
	return file_wire_demo_proto_rawDescGZIP(), []int{1}
}

func (x *ShuffledUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShuffledUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShuffledUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// OnlyID knows about field 1 and has never heard of fields 2 and 3. This is
// an old client meeting a message from a newer server: the fields it does
// not know are kept, not dropped and not an error.
type OnlyID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *OnlyID) Reset() {
	*x = OnlyID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_demo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlyID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlyID) ProtoMessage() {}

func (x *OnlyID) ProtoReflect() protoreflect.Message {
	mi := &file_wire_demo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlyID.ProtoReflect.Descriptor instead.
func (*OnlyID) Descriptor() ([]byte, []int) {
	return file_wire_demo_proto_rawDescGZIP(), []int{2}
}

func (x *OnlyID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_wire_demo_proto protoreflect.FileDescriptor

var file_wire_demo_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x77, 0x69, 0x72, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x68, 0x0a, 0x0b, 0x52, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x48, 0x0a, 0x0c, 0x53, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x18,
	0x0a, 0x06, 0x4f, 0x6e, 0x6c, 0x79, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x6f, 0x70, 0x61,
	0x74, 0x68, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wire_demo_proto_rawDescOnce sync.Once
	file_wire_demo_proto_rawDescData = file_wire_demo_proto_rawDesc
)

func file_wire_demo_proto_rawDescGZIP() []byte {
	file_wire_demo_proto_rawDescOnce.Do(func() {
		file_wire_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_wire_demo_proto_rawDescData)
	})
	return file_wire_demo_proto_rawDescData
}

var file_wire_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wire_demo_proto_goTypes = []any{
	(*RenamedUser)(nil),  // 0: wire.v1.RenamedUser
	(*ShuffledUser)(nil), // 1: wire.v1.ShuffledUser
	(*OnlyID)(nil),       // 2: wire.v1.OnlyID
}
var file_wire_demo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wire_demo_proto_init() }
func file_wire_demo_proto_init() {
	if File_wire_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wire_demo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RenamedUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_demo_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShuffledUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_demo_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OnlyID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wire_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_demo_proto_goTypes,
		DependencyIndexes: file_wire_demo_proto_depIdxs,
		MessageInfos:      file_wire_demo_proto_msgTypes,
	}.Build()
	File_wire_demo_proto = out.File
	file_wire_demo_proto_rawDesc = nil
	file_wire_demo_proto_goTypes = nil
	file_wire_demo_proto_depIdxs = nil
}
